### ISSUE TITLE
Docker app not working due to mmseqs version mismatch

### ISSUE THREAD

**Issue by josemduarte** [soedinglab/MMseqs2-App#1]
After this commit https://github.com/soedinglab/MMseqs2-App/commit/4cd0e0e6b0c891c2d8f41b3f64ff58900af1a884 the app doesn't seem to work anymore because of an error in backend when executing the search queries:
```
Unrecognized parameter --dont-shuffle
```
It seems that the docker image does not have a version of the mmseqs2 executable that supports the `--dont-shuffle` parameter, introduced in [release 4](https://github.com/soedinglab/MMseqs2/releases/tag/4-0b8cc)

**Comment by milot-mirdita** [comment]
Everything should work now in 141d981b5e0b534416733e093e6352e8bf24a89e again.

**Comment by josemduarte** [comment]
Works like a charm! Thank you!
