### ISSUE TITLE
Missing params format specification

### ISSUE THREAD

**Issue by simone-pignotti** [soedinglab/MMseqs2-App#2]
The [Params file](https://github.com/soedinglab/MMseqs2-App/blob/569d7c5/docker-compose/README.md#params-file) section in the docker-compose README is empty.
It is easy to understand the basic parameters from the examples, but it would be useful to have it in the README for quick reference.

Thanks for maintaining this amazing tool!
Simone

**Comment by josemduarte** [comment]
Indeed, it'd be great to have some docs about the params file.

For instance I was using this from an older mmseqs2-app version:
```json
{
  "display": {
    "name": "PDB protein sequence (seqres)",
    "version": "",
    "default": true,
    "order": 0
  },
  "params": {
    "search": "-s 5",
    "profile": "0",
    "maxseqlen": "32000"
  }
}
```
But following the current examples I'm now using:
```json
{
  "display": {
    "name": "PDB protein sequence (seqres)",
    "version": "",
    "default": true,
    "order": 0,
    "index": "-s 6",
    "search": "-s 6",
    "profile": "0",
    "max-accept": "--max-accept 1000"
  }
}
```
But that's purely guessing from examples and code. For instance I'd be happy to know if it was possible to customise the `--max-accept` parameter.

**Comment by josemduarte** [comment]
Actually what I would really like to do is changing the `--max-seqs` default, would that be possible with something like this?:

```json
{
  "display": {
    "name": "PDB protein sequence (seqres)",
    "version": "",
    "default": true,
    "order": 0,
    "index": "-s 6",
    "search": "-s 6",
    "profile": "0",
    "maxseqs": "--max-seqs 1000"
  }
}
```

**Comment by milot-mirdita** [comment]
Sorry for not updating this issue sooner, I was stuck on doing other stuff :(

I added a description of the params file here:
https://github.com/soedinglab/MMseqs2-App/blob/master/docker-compose/README.md

You have to stick all parameters together in a single string. This string will then be passed to MMseqs2.

The `index` and `search` properties are subject to a slightly change in the future so we can support additional search workflows (linsearch, reciprocal search, taxonomy (if I get a bachelor or master student to build this))

**Comment by simone-pignotti** [comment]
Ok, thank you very much! Could you please notify us on this issue (or by other means) if that actually evolves?
This is the classic situation which could break a docker container for people (like myself) running docker pulls in bulk and in a hurry.

**Comment by milot-mirdita** [comment]
I'll make sure to bind the docker-compose to a specific version and also provide an easy (or automated) upgrade path for the database parameters.
