### ISSUE TITLE
[Enhancement] add consensus line to alignment output

### ISSUE THREAD

**Issue by nwespe** [soedinglab/MMseqs2-App#20]
Hi, I am using the web server set up locally and it's great. I have a feature request from an end user for the alignment view. They would like to see a line between the Q and T sequences showing the match/mismatch/gap results, similar to the current NCBI BLAST output. Is this something you would consider implementing? Thanks!

**Comment by milot-mirdita** [comment]
I am using the Clustal alignment colors for this purpose, they should be visible in any modern browser (make sure your ad blocker does not disable custom fonts):
<img width="1093" alt="pairwise alignment clustal colored" src="https://user-images.githubusercontent.com/63657/114856550-863bbc00-9de7-11eb-8367-bc9a57300144.png">

I could additionally add that line if its helpful. You mean this line that contains the letter for match, `+` for similar, nothing for mismatch and `-` for gap, right?

**Comment by nwespe** [comment]
Ah, your response solves a mystery for us - this particular end user couldn't see the colors. 
Yes, that is the line I mean - I think the line would still be really helpful, since the colors make it hard to distinguish exact matches from similar, for example, and similar from mismatch. Thanks for the quick response!

**Comment by milot-mirdita** [comment]
Do you happen to know what browser the user was using?

**Comment by nwespe** [comment]
He is using Google Chrome with no apparent ad blocker.

**Comment by milot-mirdita** [comment]
Hm weird, chrome should have support for the color fonts since a long time (chrome 71 apparently).

Anyway I made a new release that contains this change (among others).

**Comment by nwespe** [comment]
Thanks!! We'll update our local version and I can also let you know if we solve the mystery of the blocked colors.

**Comment by milot-mirdita** [comment]
I made another release shortly after I wrote the last comment. Turns out the result view for multiple queries was broken in release 6.
