### ISSUE TITLE
--expand-filter-clusters

### ISSUE THREAD

**Issue by cmielke-vir** [soedinglab/MMseqs2-App#25]
The MSA job pipeline built into this app has the following line in it :

EXPAND_PARAM="--expansion-mode 0 -e ${EXPAND_EVAL} --expand-filter-clusters ${FILTER} --max-seq-id 0.95"
...
"${MMSEQS}" expandaln "${BASE}/qdb" "${DBBASE}/${DB1}.idx" "${BASE}/res" "${DBBASE}/${DB1}.idx" "${BASE}/res_exp" --db-load-mode 2 ${EXPAND_PARAM}

But it doesn't appear as though mmseqs expandaln recognizes the --expand-filter-clusters parameter. I can't find it anywhere in the source. Does this rely on an unpublished version of mmseqs?

Awesome work on ColabFold!

**Comment by milot-mirdita** [comment]
Yes this is part of my fork:
https://github.com/milot-mirdita/mmseqs2

We are working on finishing the changes up and integrating them back into the main MMseqs2 repo.

**Comment by cmielke-vir** [comment]
Right on! Thanks for the pointer. This has gotten me much closer.

One last question : I'm having trouble understanding the provenance of the uniref30_2106.idx file. Ive noticed that mmseqs2 createindex can sometimes create .idx files, but do these fundamentally differ from the .index format found in other databases that mmseqs can download through its internal databases command?

Thanks again!
