### ISSUE TITLE
MSAJob - Reg

### ISSUE THREAD

**Issue by snygt2007** [soedinglab/MMseqs2-App#26]
Hi,

I am exploring MMSeq2-App and MMSeq2 for my use case.  However, I have been facing some difficulties. I followed the instructions from "Web app quickstart with docker-compose" section. I downloaded and indexed both the uniclust30 and pdb70 databases.  The MMSeq web server is up locally on port 8877 and I am able to use the search. Q1. I am not getting the MSA job option and only the search option is visible. Please can you let me know how to invoke/execute the MSAJob option (stockholmServer False) from backend/worker.go code using the web server.

**Comment by cmielke-vir** [comment]
Like you, I've been working on getting those MSA pipelines stood up, but I'm new to the project. Take this answer with a grain of salt.

I don't think they have any of the MSA job types exposed in the web UI. Instead, they appear to only be accessible from the API, from the colabfold code for example : https://github.com/sokrypton/ColabFold/blob/8cee918b6fbbf9c9d230c46069d9e1e873898bcd/beta/colabfold.py#L67

**Comment by milot-mirdita** [comment]
It's only available through the API. No GUI for that is planned yet. We are still preparing to release the databases and scripts to setup self-hosted servers.
