### ISSUE TITLE
Large Index Files for Nucleotide Sequences

### ISSUE THREAD

**Issue by JonStargaryen** [soedinglab/MMseqs2-App#31]
Many thanks for this nice piece of software as well as MMseqs2!

I'm experiencing some strange behavior where small databases of nucleotide sequences require surprising amounts of disk space to store indices.

## Expected Behavior
- the index for a small collection of 14k nucleotide sequences (`pdb_rna_sequence`) should take much less space than the index of a large collection of 321k protein sequences (`pdb_protein_sequence`)

## Current Behavior
- `pdb_rna_sequence.idx` has a size of 8.1 GB, `pdb_protein_sequence.idx` has a size of only 1.5 GB
- when I execute `ffindex_unpack` on `pdb_rna_sequence.idx` the resulting files amount to ~50 MB

`pdb_rna_sequence.idx.index` looks like this:
```
0	0	3
1	4096	49
2	69632	412
3	61440	6145
4	8192	49153
5	77824	273617
6	352256	5931696
7	6287360	273505
8	6561792	5931696
9	13246464	33871597
10	47120384	9
12	8643059712	9
13	8643063808	9
14	8637145088	5912163
15	8637059072	9
16	8637063168	78177
18	12496896	273617
19	12771328	112717
20	12886016	273505
21	13160448	81733
22	13242368	41
23	73728	1
```

The offsets for entries 12-16 look dubious.

## Steps to Reproduce (for bugs)
Protein Params:
```
{"status":"COMPLETE","display":{"name":"PDB protein sequence (seqres)","version":"2022-01-17","path":"pdb_protein_sequence","default":true,"order":0,"index":"-s 7.5","search":"-s 7.5 --max-seqs 2000"}}
```

RNA Params:
```
{"status":"COMPLETE","display":{"name":"PDB RNA sequence (seqres)","version":"2022-01-17","path":"pdb_rna_sequence","default":false,"order":1,"index":"--search-type 3","search":"--max-seqs 2000 --search-type 3"}}
```

Sorry if this is the wrong project to submit this issue. Thank you in advance.

**Comment by JonStargaryen** [comment]
Any progress on this? Should I post this issue in the MMseqs2-repo instead?

**Comment by milot-mirdita** [comment]
I think the size of the precomputed index is expected for nucleotides. We store a couple large data structures that take a while to compute in there, one of the largest is a k-mer table that scales with the k-mer size (default k=15). It's size is thus scales to ~4^15 byte. You can generate a smaller precomputed index by specifying a smaller k-mer size, with some speed-sensitivity tradeoffs.

**Comment by milot-mirdita** [comment]
`ffindex_unpack` won't work in this case since some of the lengths in the idx.index are wrong (max length is 4gb, afterwards the length overflow, the offsets don't have this issue). Also I think `ffindex_unpack` might not deal well with binary data (null bytes).

**Comment by JonStargaryen** [comment]
Oh, I see. Just wanted to make sure. Thank you Milot!
