### ISSUE TITLE
Docker images versioning

### ISSUE THREAD

**Issue by josemduarte** [soedinglab/MMseqs2-App#4]
I use this fantastic app from the available docker containers. However there only seems to be a `latest` tag available in docker hub. The `latest` tag seems to be tracking every commit in master.

For reproducibility and stability purposes it would help if there were tags available with stable releases, so that production services could point to a certain stable tag instead of latest. Otherwise production services can break unexpectedly if a bug is introduced.

**Comment by simone-pignotti** [comment]
This would be very useful indeed!

**Comment by simone-pignotti** [comment]
In my opinion the main version number should match the mmseqs2 release used. The minor version number could then be used to reflect changes in the web backend/frontend.

**Comment by milot-mirdita** [comment]
I setup Docker Hub to now tag Docker images with their respective version string for future releases.

**Comment by josemduarte** [comment]
That's great news, thank you so much @milot-mirdita !

**Comment by simone-pignotti** [comment]
Great, thank you!

**Comment by milot-mirdita** [comment]
The images are now tagged and docker-compose references the specific version in its `.env` file (currently version-2).
