### ISSUE TITLE
App does not work with latest mmseqs version

### ISSUE THREAD

**Issue by samirelanduk** [soedinglab/MMseqs2-App#61]
I am trying to replicate the commands that run in `worker.go` - specifically the `MsaJob` script that starts at: https://github.com/soedinglab/MMseqs2-App/blob/59f2761c2f215ed05e3c99879e97fa578f7c12cb/backend/worker.go#L273

When trying to run the `expandaln` line:

```bash
"${MMSEQS}" expandaln "${BASE}/qdb" "${DB1}.idx" "${BASE}/res" "${DB1}.idx" "${BASE}/res_exp" ${EXPAND_PARAM}
```

I get the error:

`Unrecognized parameter "--expand-filter-clusters". Did you mean "--expansion-mode" (Expansion mode)?`

This is using mmseqs 13-45111 (the latest version) - is the app supposed to be used with an older version of mmseqs which supported this parameter? Or with a modified/dev version of it?

I encountered a similar issue with some of the other scripts.

To clarify I have not spun up the entire app, I am just trying to get that generated bash script to run in isolation against the latest mmseqs command line tool. Is there something I'm missing?

**Comment by samirelanduk** [comment]
Looks like this app uses a much more recent commit of mmseqs, whereas there hasn't been an official release of mmseqs in some time so the version installable with (for example) Brew doesn't work with this app. I guess this can be resolved by just using the Dockerfile provided here to build the relevant mmseqs.

**Comment by milot-mirdita** [comment]
The latest MMseqs2 release 14 includes everything required to run the app.
