### ISSUE TITLE
Web app search fails with error

### ISSUE THREAD

**Issue by padix-key** [soedinglab/MMseqs2-App#94]
Hi,

I tried multiple sequence searches at https://seqsearch.east.k8s.rcsb.org/ (I assume this web server is associated with you?). However, all searches, even the one with the *default* sequence failed with the following error: `No record of this job submission exists.`

**Comment by martin-steinegger** [comment]
No its hosted by the rcsb. We have not control over it.

**Comment by josemduarte** [comment]
> I tried multiple sequence searches at https://seqsearch.east.k8s.rcsb.org/ (I assume this web server is associated with you?

That is an RCSB PDB development server. There's no assumptions that the server will work or that it will stay around at all. I'm curious, how did you come across it? For production we do use this app but we don't expose it to the public. However we do expose sequence search via our Search API. See details at https://search.rcsb.org

**Comment by padix-key** [comment]
OK, good to know, thanks for the info. Just a quick Google search for `mmseqs web server` yielded it as a top hit
